name: "DDN Deployment"
description: "Deploy to a Hasura DDN environment"
branding:
  icon: package
  color: white
inputs:
  hasura-pat:
    description: "Your PAT, preferably saved as a secret in your repository"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install ddn CLI
      shell: bash
      run: |
        curl -L https://graphql-engine-cdn.hasura.io/ddn/cli/v2/get.sh | bash
    - name: Login to ddn
      shell: bash
      run: ddn auth login --pat ${{ inputs.hasura-pat }}
