name: "DDN Deployment"
description: "Deploy to a Hasura DDN environment"
branding:
  icon: package
  color: white
inputs:
  hasura-pat:
    description: "Your PAT, preferably saved as a secret in your repository"
    required: true
  supergraph_manifest:
    description: "The name of the supergraph manifest to use for the build."
    required: true
    default: "DefaultSupergraphManifest"
  build_description:
    description: "A description to alert other users that this build was created using CI/CD"
    required: true
    default: "CI/CD via ddn-deployment GitHub Action"
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create and apply build
      run: |
        curl -L https://graphql-engine-cdn.hasura.io/ddn/cli/latest/cli-hasura3-linux-amd64 -o ddn
        chmod +x ddn
        sudo mv ddn /usr/local/bin
        ddn login --pat ${{ inputs.hasura-pat }}
        OUTPUT=$(ddn build supergraph --s ${{ inputs.supergraph_manifest }} --description "${{ inputs.build_description }}" --out json)
        BUILD_VERSION=$(echo $OUTPUT | jq -r '.build_version')
        ddn apply supergraph-build $BUILD_VERSION
      shell: bash
